grade_class_one = input ('What grade do you have in FAT? ')
print ('So in FAT, your grade is' ,grade_class_one)
credit_class_one = input ('How much credit/s is the class worth? ')
print ("In " + "FAT " + "you have " + credit_class_one + " credits.")
grade_class_two = input ('What grade do you have in Writing 121? ')
print ('So in Writing 121, your grade is' ,grade_class_two)
credit_class_two = input ('How much credit/s is the class worth? ')
print ("In " + "Writing 121 " + "you have " + credit_class_one + " credits.")
grade_class_three = input ('What grade do you have in CAD 1? ')
print ('So in CAD 1, your grade is' ,grade_class_three)
credit_class_three = input ('How much credit/s is the class worth? ')
print ("In " + "CAD 1 " + "you have " + credit_class_one + " credits.")
grade_class_four = input ('What grade do you have in AP Computer Science Principles? ')
print ('So in AP Computer Science Principles, your grade is' ,grade_class_four)
credit_class_four = input ('How much credit/s is the class worth? ')
print ("In " + "AP Computer Science Principles " + "you have " + credit_class_one + " credits.")
total_gpa = grade_class_one + grade_class_two + grade_class_three + grade_class_four
print("Your GPA is: " + total_gpa)

